engines:
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true
  bundler-audit:
    enabled: true

ratings:
  paths:
  - Gemfile.lock
  - "**.js"
  - "**.jsx"

exclude_paths:
  - newrelic.js
